apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-demo-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ViktorKnu/KubeLaunch.git
    targetRevision: main
    path: apps/ai-demo/backend/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-demo
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: ai-demo-backend
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
