apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-smoke-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ViktorKnu/KubeLaunch.git
    targetRevision: main
    path: apps/platform-smoke-test
  destination:
    server: https://kubernetes.default.svc
    namespace: kubelaunch-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
